FROM node:18
WORKDIR /app
COPY package.json .
RUN npm install --verbose


# obsolete wenn using a VOLUME
#COPY . .

# actually obsolete - defined as default in base image
EXPOSE 3000

CMD [ "npm", "start" ]